# Generated by Django 5.1.2 on 2026-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
